from django.conf.urls import patterns, url
from ems.views import *
urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^login/$', user_login, name='user_login'),
    url(r'^logout/$', user_logout, name='user_logout'),
    # url(r'^uploadlist/$', upload_list, name='upload_list'),
    # url(r'^chooseLeader/$', choose_leader, name='choose_leader'),
    # url(r'^genTeam/$', genTeam, name='genTeam'),
    # url(r'^addbitsian/$', bitsian_add, name='add_bitsian'),
    # url(r'^participantdetails/(?P<partid>\d+)/$', participant_details, name="participant_details"),
    # url(r'^participantdetails/$', participant_details_home, name="participant_home"),
    url(r'^events/$', events_select, name="events_select"),
    url(r'^events/(?P<eventid>\d+)/setup/$', events_levels, name="events_levels"),
    url(r'^events/(?P<eventid>\d+)/judge/$', events_judge_home, name="events_judge_home"),
    url(r'^events/(?P<eventid>\d+)/participants/$', events_participants, name="events_participants"),
    url(r'^events/(?P<eventid>\d+)/participants/add/$', events_participants_add, name="events_participants_add"),
    url(r'^events/(?P<eventid>\d+)/teams/$', events_teams, name="events_teams"),
    url(r'^events/(?P<eventid>\d+)/teams/add/$', events_teams_add, name="events_teams_add"),
    url(r'^events/(?P<eventid>\d+)/teams/edit/(?P<teamid>\d+)/$', events_teams_edit, name="events_teams_edit"),
    url(r'^events/(?P<eventid>\d+)/levels/add/$', events_levels_add, name="events_levels_add"),
    url(r'^events/(?P<eventid>\d+)/judges/add/$', events_judges_add, name="events_judges_add"),
    url(r'^events/(?P<eventid>\d+)/labels/add/$', events_labels_add, name="events_labels_add"),
    url(r'^events/(?P<eventid>\d+)/levels/(?P<levelid>\d+)/edit/$', events_levels_edit, name="events_levels_edit"),
    url(r'^events/(?P<eventid>\d+)/levels/(?P<levelid>\d+)/judge/(?P<judgeid>\d+)/login/$', events_judge_login, name="events_judge_login"),
    url(r'^events/(?P<eventid>\d+)/levels/(?P<levelid>\d+)/judge/(?P<judgeid>\d+)/$', events_levels_judge, name="events_levels_judge"),
    url(r'^events/(?P<eventid>\d+)/home/$', events_home, name="events_home"),
    # url(r'^teamdetails/(?P<teamid>\d+)/$', team_details, name="team_details"),
    # url(r'^teamdetails/$', team_details_home, name="team_home"),
	# url(r'^getparticipantlist/$', getParticipantList, name='getParticipantList'),
]
